# Generated by Django 4.2.6 on 2023-10-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heladera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('tipo_freezer', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Televisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=30)),
                ('tamano_pantalla', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='cocina',
            name='tipo_gas',
            field=models.CharField(max_length=40),
        ),
    ]
