# Generated by Django 4.2.6 on 2023-11-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_heladera_televisor_alter_cocina_tipo_gas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocina',
            name='precio',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heladera',
            name='precio',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='televisor',
            name='precio',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cocina',
            name='marca',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cocina',
            name='modelo',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='heladera',
            name='marca',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='heladera',
            name='modelo',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='televisor',
            name='marca',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='televisor',
            name='modelo',
            field=models.CharField(max_length=40),
        ),
    ]
